site_name: Scratch OS Wiki
nav:
  - 主页: index.md
  - 数据库:
      - COLID Studio: ./colid-studio/colid-studio.md
      - MengteOS: ./MengteOS/MengteOS.md
      - floaOS: ./floaos/floa OS.md
theme:
  name: material
