里site_name: Scratch OS Wiki

nav:
  - 主页: index.md
  - 数据库:
    - COLID Studio: ./colid-studio/colid-studio.md
    - MengteOS: ./MengteOS/MengteOS.md
    - floa OS: ./floa os/floa OS.md
  - 活动:
    - scratchOS接力创作大赛: ./achive/hueuos.md
  - 历史:
theme:
  name: material
